### PR TITLE
WAMP Authentication protocols and API changes

### PR DESCRIPTION
**Pull request by eukreign**
Made API closer to AutobahnPython and added WAMP Authentication protocol.

### CODE REVIEW

**Comment by eukreign** [comment]
Thanks @maxpersson 

I'm not using Dart anymore and would like to delete my fork of dart-wamp but it seems like @gmosx is not going to merge these changes (it's been 6 months after all).

If you are benefiting from these changes would you mind forking my fork so that I can delete it?

**Comment by maxekman** [comment]
Thanks for letting me know, I have forked your repo in case I need the code (I have not started on the dart side of the project yet). You can go ahead and remove your for if you want.

**Comment by gtaylor** [comment]
@gmosx Any chance this will be landing in master? I could really use authentication, myself.

On a side note, if you are no longer interested in maintaining this package, please do speak up so we can figure out where to go from here. There's no shame in it.

**Comment by gmosx** [comment]
Ooops, I missed that pull request, will take care of it later today!

-g.

**Comment by gtaylor** [comment]
Bueller?

**Pull request closed without merging**
